#surcharge des routes de FOSUser pour les passer en français
fos_user_security_login:
    path: /connexion
    defaults: {_controller:FOSUserBundle:Security:login}

fos_user_security_check:
    path: /verif
    defaults: {_controller:FOSUserBundle:Security:check}

fos_user_security_logout:
    path: /deconnexion
    defaults: {_controller:FOSUserBundle:Security:logout}
