parameters:
#    e_shop_admin.example.class: EShop\AdminBundle\Example

services:
#    e_shop_admin.example:
#        class: %e_shop_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
