Livraison:
    type: entity
    table: livraison
    indexes:
        FK_LIVRAISON_DPT:
            columns:
                - departement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        cp:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        ville:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        livree:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
    manyToOne:
        departement:
            targetEntity: Departement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                departement:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
