article:
    path:     /
    defaults: { _controller: "EShopAdminBundle:article:index" }

article_show:
    path:     /{id}/voir
    defaults: { _controller: "EShopAdminBundle:article:show" }

article_new:
    path:     /nouveau
    defaults: { _controller: "EShopAdminBundle:article:new" }

article_create:
    path:     /creer
    defaults: { _controller: "EShopAdminBundle:article:create" }
    requirements: { _method: post }

article_edit:
    path:     /{id}/editer
    defaults: { _controller: "EShopAdminBundle:article:edit" }

article_update:
    path:     /{id}/mettreAjour
    defaults: { _controller: "EShopAdminBundle:article:update" }
    requirements: { _method: post|put }

article_delete:
    path:     /{id}/supprimer
    defaults: { _controller: "EShopAdminBundle:article:delete" }
    requirements: { _method: post|delete }
